import { resolve } from 'node:path'
import { test } from '@playwright/test'
import { acceptCase, classify, finishCase, investigateBestPath, scenario, takeAction } from './helpers'

const shot = (name: string) => resolve('artifacts/screenshots', name)

test('captures the required responsive visual QA matrix', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await page.screenshot({ path: shot('1440x900-landing.png'), animations: 'disabled' })
  await page.goto('/shifts')
  await page.screenshot({ path: shot('1440x900-shift-board.png'), animations: 'disabled' })

  const dns = scenario('SD-001')
  await acceptCase(page, dns.id)
  for (const id of dns.debrief.bestPathActionIds.slice(0, 4)) await takeAction(page, dns, id)
  await page.screenshot({ path: shot('1440x900-dns-four-clues.png'), animations: 'disabled' })
  await page.screenshot({ path: shot('1440x900-active-case.png'), animations: 'disabled' })
  for (const id of dns.debrief.bestPathActionIds.slice(4)) await takeAction(page, dns, id)
  await classify(page, 'dns-timeout', 'stale-dns', 'Supports')
  await classify(page, 'public-ip-success', 'organization-outage', 'Contradicts')
  await finishCase(page, dns)
  await page.screenshot({ path: shot('1440x900-dns-debrief.png'), animations: 'disabled' })
  await page.screenshot({ path: shot('1440x900-debrief.png'), animations: 'disabled' })

  await page.evaluate(() => localStorage.clear())
  await page.setViewportSize({ width: 1024, height: 768 })
  const training = scenario('TRAIN-001')
  await acceptCase(page, training.id)
  await page.screenshot({ path: shot('1024x768-active-actions.png'), animations: 'disabled' })
  await investigateBestPath(page, training)
  await page.getByRole('button', { name: 'Commit decision' }).click()
  await page.screenshot({ path: shot('1024x768-decision.png'), animations: 'disabled' })

  await page.evaluate(() => localStorage.clear())
  await page.setViewportSize({ width: 768, height: 1024 })
  await page.goto('/case/TRAIN-001/briefing')
  await page.screenshot({ path: shot('768x1024-briefing.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Accept case' }).click()
  await page.screenshot({ path: shot('768x1024-active.png'), animations: 'disabled' })

  await page.evaluate(() => localStorage.clear())
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.screenshot({ path: shot('390x844-landing.png'), animations: 'disabled' })
  await acceptCase(page, training.id)
  await page.screenshot({ path: shot('390x844-active-evidence.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  await page.screenshot({ path: shot('390x844-actions-sheet.png'), animations: 'disabled' })
  await page.screenshot({ path: shot('390x844-active-actions-open.png'), animations: 'disabled' })
  for (const id of training.debrief.bestPathActionIds) await takeAction(page, training, id)
  await page.getByRole('button', { name: 'Close actions' }).click()
  await classify(page, 'selected-output', 'wrong-output', 'Supports')
  await classify(page, 'scope-audio', 'driver-failure', 'Contradicts')
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  await page.getByRole('button', { name: 'Commit decision' }).click()
  await page.getByLabel(training.decision.options.find((item) => item.isCorrect)!.label).check()
  await page.getByLabel('Confidence').selectOption('high')
  await page.getByLabel('Verification plan').selectOption(training.verification.options.find((item) => item.isCorrect)!.id)
  await page.getByRole('button', { name: 'Commit decision', exact: false }).click()
  await page.getByLabel(training.resolution.options.find((item) => item.isCorrect)!.label).check()
  await page.getByRole('button', { name: 'Choose resolution' }).click()
  await page.screenshot({ path: shot('390x844-verification.png'), animations: 'disabled' })
  await page.getByLabel(training.verification.options.find((item) => item.isCorrect)!.label).check()
  await page.getByRole('button', { name: 'Verify outcome' }).click()
  for (const id of training.communication.requiredMessageParts) await page.getByLabel(training.communication.availableMessageParts.find((item) => item.id === id)!.text).check()
  await page.getByRole('button', { name: 'Complete handoff' }).click()
  await page.screenshot({ path: shot('390x844-debrief.png'), animations: 'disabled' })

  await page.evaluate(() => localStorage.clear())
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.screenshot({ path: shot('320x568-landing.png'), animations: 'disabled' })
  await acceptCase(page, dns.id)
  await page.screenshot({ path: shot('320x568-active.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  await page.screenshot({ path: shot('320x568-actions-open.png'), animations: 'disabled' })
  await page.locator('.more-tests > summary').click()
  await page.locator('.action-drawer').evaluate((element) => { element.scrollTop = element.scrollHeight })
  await page.screenshot({ path: shot('320x568-actions-scrolled-end.png'), animations: 'disabled' })
  const prohibited = dns.actions.find((item) => item.id === 'restart-router')!
  await page.locator('.action-card').filter({ has: page.getByRole('heading', { name: prohibited.label }) }).getByRole('button', { name: 'Take action' }).click()
  await page.screenshot({ path: shot('320x568-impact-confirmation.png'), animations: 'disabled' })
})
