// Generated by scripts/generate-content-index.ts. Do not edit.
import scenario0 from './scenarios/ID-001-impossible-travel.json'
import scenario1 from './scenarios/SD-001-no-names-only-numbers.json'
import scenario2 from './scenarios/SOC-001-help-desk-is-calling.json'
import scenario3 from './scenarios/TRAIN-001-wrong-output.json'
import { validateScenarioCollection } from '../engine/validation'

export const scenarios = validateScenarioCollection([scenario0, scenario1, scenario2, scenario3])
export const scenarioById = new Map(scenarios.map((scenario) => [scenario.id, scenario]))
