import { readdirSync, writeFileSync } from 'node:fs'
import { basename, resolve } from 'node:path'

const directory = resolve('src/content/scenarios')
const output = resolve('src/content/generated.ts')
const files = readdirSync(directory).filter((file) => file.endsWith('.json')).sort()
const imports = files.map((file, index) => `import scenario${index} from './scenarios/${basename(file)}'`).join('\n')
const values = files.map((_, index) => `scenario${index}`).join(', ')
const source = `// Generated by scripts/generate-content-index.ts. Do not edit.\n${imports}\nimport { validateScenarioCollection } from '../engine/validation'\n\nexport const scenarios = validateScenarioCollection([${values}])\nexport const scenarioById = new Map(scenarios.map((scenario) => [scenario.id, scenario]))\n`

writeFileSync(output, source, 'utf8')
console.log(`Generated typed index for ${files.length} scenarios.`)
